{% set name = "molecule-docker" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/molecule-docker-{{ version }}.tar.gz
  sha256: 5ca49d2921c5a7191e227249ad5a6a9d66c38b5e07ae6ef1d5c721f5436a582a

build:
  number: 0
  skip: true  # [py < 37 or win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0
  run:
    - docker-py >=4.3.1
    - molecule >=3.0.2
    - python
    - python-selinux  # [linux]

test:
  imports:
    - molecule_docker
    - molecule_docker.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ansible-community/molecule-docker
  summary: Molecule aids in the development and testing of Ansible roles
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
