{% set name = "molecule-docker" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/molecule-docker-{{ version }}.tar.gz
  sha256: e15133395f10dbf60f75125aae7145f47747fc7158f2317698885013796252bf

build:
  number: 1
  skip: true  # [py < 38 or win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0
  run:
    - docker-py >=4.3.1
    - molecule >=3.4.0
    - python
    - python-selinux  # [linux]
    - ansible-compat >=0.5.0
    - requests

test:
  imports:
    - molecule_docker
    - molecule_docker.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ansible-community/molecule-docker
  summary: Molecule aids in the development and testing of Ansible roles
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
