{% set name = "molecule-docker" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/molecule-docker-{{ version }}.tar.gz
  sha256: 12c180c95c3f022d89aedd52e42b57e5c1e0ee4d4be8ec997c3dcb9c28d7e2a3

build:
  number: 0
  skip: true  # [py < 38 or win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - docker-py >=4.3.1
    - molecule >=4.0.0
    - python
    - python-selinux  # [linux]
    - requests

test:
  imports:
    - molecule_docker
    - molecule_docker.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ansible-community/molecule-docker
  summary: Molecule aids in the development and testing of Ansible roles
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
